### ISSUE TITLE
大佬 这个主题怎么安装的

### ISSUE THREAD

**Issue by mucstudio** [acccccccb/FirgateBird-theme-for-wordpress#2]
大佬 这个主题怎么安装的，跟正常的不一样啊，

**Comment by acccccccb** [comment]
部署前需要安装node环境，在你本机或者服务器都行。
在项目中运行：
npm i
npm run build

然后把生成的dist文件夹拷贝到 /wp-content/themes
然后将文件夹名称改为 FrigateBird，之后在主题管理页面就能看见了
